/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tirta_Maju_Abadi.View;

import Tirta_Maju_Abadi.DataModel.MD_Bahan_metah;
import Tirta_Maju_Abadi.DataModel.listMD_Bahan_mentah;
import Tirta_Maju_Abadi.Report.InvoiceDesign;
import Tirta_Maju_Abadi.View.evetView.Model_view_bahan_mentah;
import Tirta_Maju_Abadi.toll.database;
import Tirta_Maju_Abadi.toll.loadAllData;

/**
 *
 * @author jepank's
 */
public class Bahan_mentah extends javax.swing.JInternalFrame {

    private MD_Bahan_metah mbm=new MD_Bahan_metah();
    private Model_view_bahan_mentah mvb;
    private database db;
    private loadAllData lad;
    /**
     * Creates new form Bahan_mentah
     */
    
    public Bahan_mentah(database db, loadAllData lad){
        initComponents();
        mvb=new Model_view_bahan_mentah(t_Bahan_mentah.getModel(), db, lad);
        this.db=db;
        this.lad=lad;
        reset();
    }
    
    private void reset(){
        flipflapBot(true);
        f_id_bahan.setText(mvb.reset());
        f_nama_bahan.reset();
        f_unit.reset();
        f_limit.reset();
        f_spesifikasi.setText("");
        f_stock.reset();
        f_nama_bahan.requestFocus(true);
    }
    
    private void flipflapBot(boolean tmp){
        jButton1.setEnabled(tmp);
        jButton2.setEnabled(!tmp);
    }
    private boolean cekKosong(){
        return f_nama_bahan.Kosongkah()
                &&f_stock.Kosongkah()
                &&f_limit.Kosongkah()
                &&!f_spesifikasi.getText().equals("")
                &&f_unit.Kosongkah();
                
    }
    
    private MD_Bahan_metah getToMD(){
        MD_Bahan_metah tmp=null;
        if(cekKosong())
            tmp=new MD_Bahan_metah(f_id_bahan.getInteger(), f_stock.getInteger(),f_limit.getInteger(),
                    f_nama_bahan.getString(), f_unit.getString(), f_spesifikasi.getText(), lad);
        return tmp;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_nama_bahan = new javax.swing.JLabel();
        jl_unit = new javax.swing.JLabel();
        jl_stock = new javax.swing.JLabel();
        jl_limit = new javax.swing.JLabel();
        f_nama_bahan = new Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt(jl_nama_bahan);
        f_unit = new Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt(jl_unit);
        f_stock = new Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt(jl_stock);
        f_limit = new Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt(jl_limit);
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_Bahan_mentah = new javax.swing.JTable();
        jl_spesifikasi = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        f_spesifikasi = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jl_bahan_mentah = new javax.swing.JLabel();
        f_id_bahan = new Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt(jl_bahan_mentah);
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4), "Bahan Mentah", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        jl_nama_bahan.setText("Nama Bahan");

        jl_unit.setText("Unit");

        jl_stock.setText("Stock");

        jl_limit.setText("Limit Buffer");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 4), "Tabel Bahan Mentah", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        t_Bahan_mentah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Barang", "Unit", "Stock", "Limit Buffer", "Spesifikasi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_Bahan_mentah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_Bahan_mentahMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(t_Bahan_mentah);
        if (t_Bahan_mentah.getColumnModel().getColumnCount() > 0) {
            t_Bahan_mentah.getColumnModel().getColumn(0).setResizable(false);
            t_Bahan_mentah.getColumnModel().getColumn(0).setPreferredWidth(50);
            t_Bahan_mentah.getColumnModel().getColumn(1).setResizable(false);
            t_Bahan_mentah.getColumnModel().getColumn(1).setPreferredWidth(120);
            t_Bahan_mentah.getColumnModel().getColumn(2).setResizable(false);
            t_Bahan_mentah.getColumnModel().getColumn(2).setPreferredWidth(70);
            t_Bahan_mentah.getColumnModel().getColumn(3).setResizable(false);
            t_Bahan_mentah.getColumnModel().getColumn(3).setPreferredWidth(70);
            t_Bahan_mentah.getColumnModel().getColumn(4).setResizable(false);
            t_Bahan_mentah.getColumnModel().getColumn(4).setPreferredWidth(70);
            t_Bahan_mentah.getColumnModel().getColumn(5).setResizable(false);
            t_Bahan_mentah.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jl_spesifikasi.setText("Spesifikasi");

        f_spesifikasi.setColumns(20);
        f_spesifikasi.setRows(5);
        jScrollPane3.setViewportView(f_spesifikasi);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tirta_Maju_Abadi/Images/simpan.png"))); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tirta_Maju_Abadi/Images/edit.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jl_bahan_mentah.setText("Id Bahan");

        f_id_bahan.setEditable(false);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tirta_Maju_Abadi/Images/Reset.png"))); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_nama_bahan)
                            .addComponent(jl_unit)
                            .addComponent(jl_bahan_mentah)
                            .addComponent(jl_stock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f_nama_bahan, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(f_unit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f_id_bahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_limit)
                            .addComponent(jl_spesifikasi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(f_limit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_bahan_mentah)
                    .addComponent(f_id_bahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_limit)
                    .addComponent(f_limit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_spesifikasi)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_nama_bahan)
                                    .addComponent(f_nama_bahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_unit)
                                    .addComponent(f_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_stock)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(f_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(11, 11, 11)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MD_Bahan_metah tmp=getToMD();
        if(tmp!=null){
            mvb.Insert(tmp);
            reset();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MD_Bahan_metah tmp=getToMD();
        if(tmp!=null){
            mvb.Update(tmp);
            reset();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_Bahan_mentahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_Bahan_mentahMousePressed
        // TODO add your handling code here:
        MD_Bahan_metah mb=(MD_Bahan_metah)t_Bahan_mentah.getValueAt(t_Bahan_mentah.getSelectedRow(), 1);
        f_id_bahan.setText(mb.getId_bahan());
        f_nama_bahan.setText(mb.getNama_bahan());
        f_unit.setText(mb.getUnit());
        f_stock.setText(mb.getStok());
        f_limit.setText(mb.getLimit_buffer());
        f_spesifikasi.setText(mb.getSpesifikasi());
        flipflapBot(false);
        
    }//GEN-LAST:event_t_Bahan_mentahMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new InvoiceDesign();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt f_id_bahan;
    private Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt f_limit;
    private Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt f_nama_bahan;
    private javax.swing.JTextArea f_spesifikasi;
    private Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt f_stock;
    private Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt f_unit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jl_bahan_mentah;
    private javax.swing.JLabel jl_limit;
    private javax.swing.JLabel jl_nama_bahan;
    private javax.swing.JLabel jl_spesifikasi;
    private javax.swing.JLabel jl_stock;
    private javax.swing.JLabel jl_unit;
    private javax.swing.JTable t_Bahan_mentah;
    // End of variables declaration//GEN-END:variables
}
