/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tirta_Maju_Abadi.View;

import Tirta_Maju_Abadi.DataModel.MD_Mobil;
import Tirta_Maju_Abadi.DataModel.MD_Pegawai;
import Tirta_Maju_Abadi.DataModel.list2Values;
import Tirta_Maju_Abadi.View.evetView.Model_view_Mobil;
import Tirta_Maju_Abadi.toll.database;
import Tirta_Maju_Abadi.toll.loadAllData;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author NEEZAR
 */
public class Mobil extends javax.swing.JInternalFrame {
    private Model_view_Mobil mvb;
    private database db;
    private loadAllData lad;
    private MD_Mobil mm = new MD_Mobil();
    /**
     * Creates new form Mobil
     */
    public Mobil(database db, loadAllData lad ) {
        initComponents();
        this.db= db;
        this.lad=lad;
        mvb= new Model_view_Mobil(t_armada.getModel(),db,lad,mm);
        
        SetDriver();
        reset();
    }
    private void SetDriver()
    {
        for(MD_Pegawai tmp:lad.getListMD_Pegawai().getListDriver())
        {
            c_driver.addItem(tmp);
        }
    }
    
    private void SetHelper()
    {
        for(MD_Pegawai tmp:lad.getListMD_Pegawai().getListHelper())
        {
        c_helper.addItem(tmp);
        }
    }
           
    private void SetType()
    {
        c_type.addItem(mm.ListType());
    }
    private void reset(){
        f_nopol.reset();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_armada = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ban41 = new Tirta_Maju_Abadi.View.ban4();
        ban61 = new Tirta_Maju_Abadi.View.ban6();
        ban101 = new Tirta_Maju_Abadi.View.ban10();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        f_nopol = new Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt(jLabel1);
        c_type = new Tirta_Maju_Abadi.View.ModelSwing.ModelChuser();
        jLabel4 = new javax.swing.JLabel();
        c_driver = new Tirta_Maju_Abadi.View.ModelSwing.ModelChuser();
        c_helper = new Tirta_Maju_Abadi.View.ModelSwing.ModelChuser();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Tabel Armada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        t_armada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nopol", "Driver Atau Helper", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_armada.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(t_armada);
        if (t_armada.getColumnModel().getColumnCount() > 0) {
            t_armada.getColumnModel().getColumn(0).setResizable(false);
            t_armada.getColumnModel().getColumn(0).setPreferredWidth(1);
            t_armada.getColumnModel().getColumn(1).setResizable(false);
            t_armada.getColumnModel().getColumn(1).setPreferredWidth(100);
            t_armada.getColumnModel().getColumn(2).setResizable(false);
            t_armada.getColumnModel().getColumn(2).setPreferredWidth(180);
            t_armada.getColumnModel().getColumn(3).setResizable(false);
            t_armada.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(ban41, "card2");
        jPanel2.add(ban61, "card3");
        jPanel2.add(ban101, "card4");

        jLabel1.setText("Nopol ");

        jLabel2.setText("Driver");

        jLabel3.setText("Type");

        c_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "Item 1", "Item 2", "Item 3" }));
        c_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c_typeItemStateChanged(evt);
            }
        });

        jLabel4.setText("Helper");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tirta_Maju_Abadi/Images/Reset.png"))); // NOI18N
        jButton1.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(c_driver, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(c_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(f_nopol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(c_helper, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(f_nopol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(c_driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(c_helper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(c_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c_typeItemStateChanged
        // TODO add your handling code here:
        if(c_type.getSelectedItem().equals("Item 1")){
            ban61.setVisible(false);
            ban101.setVisible(false);
            ban41.setVisible(true);
        }
        else if(c_type.getSelectedItem().equals("Item 2")) {
            ban41.setVisible(false);
            ban101.setVisible(false);
            ban61.setVisible(true);
        }
        else if(c_type.getSelectedItem().equals("Item 3")) {
            ban41.setVisible(false);
            ban101.setVisible(true);
            ban61.setVisible(false);
        }
    }//GEN-LAST:event_c_typeItemStateChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Tirta_Maju_Abadi.View.ban10 ban101;
    private Tirta_Maju_Abadi.View.ban4 ban41;
    private Tirta_Maju_Abadi.View.ban6 ban61;
    private Tirta_Maju_Abadi.View.ModelSwing.ModelChuser c_driver;
    private Tirta_Maju_Abadi.View.ModelSwing.ModelChuser c_helper;
    private Tirta_Maju_Abadi.View.ModelSwing.ModelChuser c_type;
    private Tirta_Maju_Abadi.View.ModelSwing.modelTextFilt f_nopol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_armada;
    // End of variables declaration//GEN-END:variables
}
